# Generated by Django 4.2.11 on 2025-12-20 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("PAID", "Paid"),
                        ],
                        default="BOOKED",
                        max_length=12,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("assigned_room", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("location", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("RESIDENT", "Resident"),
                            ("ATTENDING", "Attending"),
                            ("CHIEF", "Chief Physician"),
                        ],
                        default="RESIDENT",
                        max_length=16,
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("available_slots_per_day", models.PositiveIntegerField(default=20)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctors",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("id_card", models.CharField(max_length=18, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("SELF", "Self Pay"),
                        ],
                        default="PUBLIC",
                        max_length=8,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("AM", "Morning"),
                            ("PM", "Afternoon"),
                            ("EV", "Evening"),
                        ],
                        max_length=2,
                    ),
                ),
                ("room_no", models.CharField(blank=True, max_length=16)),
                ("capacity", models.PositiveIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("FULL", "Full"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="core.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("prescription", models.TextField(blank=True)),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record",
                        to="core.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="core.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
            },
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "insurance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "self_pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("INSURANCE", "Insurance Direct"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "medical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="core.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing",
                "verbose_name_plural": "Billings",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                check=models.Q(("capacity__gte", 1)), name="schedule_capacity_positive"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("doctor", "date", "time_slot")},
        ),
        migrations.AlterUniqueTogether(
            name="doctor",
            unique_together={("name", "department")},
        ),
        migrations.AddConstraint(
            model_name="billing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("total_amount__gte", 0),
                    ("insurance_amount__gte", 0),
                    ("self_pay_amount__gte", 0),
                ),
                name="billing_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="billing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "total_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("insurance_amount"),
                            "+",
                            models.F("self_pay_amount"),
                        ),
                    )
                ),
                name="billing_amount_consistency",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("patient", "schedule")},
        ),
    ]
